name: "Compilation and tests"

on:
  push:
  pull_request:
  schedule:
    # 1st and 15th days of each month at 4:30 UTC
    - cron:  '30 4 1,15 * *'
  # Possibility for manual run
  workflow_dispatch:

jobs:
  compile:
    name: "Compilation and tests"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout to workspace
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: setupCiWorkspace

    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: build

    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: test
